# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8f221169e595f5b3694ed0dde8d0037ad48afafd90c9bac60009780329daa48df22badb1971a5d567039069bb1d7cf05fb1d3ef9b61224fb34029877b9e82d

test:
  secret_key_base: a3721224289a8a73e685dcdc7413684616b9ea70cc3178a4e789db5b39605ccd0389c0944a6381ffc4fe7889ebdb0e512c886d321fa2b1631f863b4611f7eb93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
